### PR TITLE
G2-756 Public release

### PR DESCRIPTION
**Pull request by gdgib**
Depends on https://github.com/g2forge/enigma/pull/86, https://github.com/g2forge/alexandria/pull/262, https://github.com/g2forge/bulldozer/pull/53, https://github.com/g2forge/habitat/pull/26, https://github.com/g2forge/gearbox/pull/67, https://github.com/g2forge/reassert/pull/4

### CODE REVIEW

**Comment by Fakerr** [comment]
Hey, curious here. Since this PR depends on other ones, would you be interested by this [Github app](https://www.dpulls.com/) that I built that prevents PRs with "Depends on" from being merged before their dependencies ? Do you think it's something that can help you in your projects ? cc @gdgib

**Comment by gdgib** [comment]
@Fakerr maybe, but I can't find either licensing or payment information in a quick scan of your website, and GH org.  Let me know if I'm missing something, would you?

**Comment by Fakerr** [comment]
@gdgib The app is a hosted app, so it doesn't really need a license, and for the payment page, it's in construction right now but to summarize, it's gonna be completely free for OSS projects and we will charge a small amount for private repositories in the future (For now, even private repos are free).

**Comment by gdgib** [comment]
Sorry, without any document to codify what you'll do with the access I grant you and your software, we are absolutely not interested in the security, privacy or legal risks associated with your product.  Thanks anyway, and all the best!

**Comment by gdgib** [comment]
Note for the future: this discussion was taken offline.

**Pull request merged**
